services:
  - type: web
    name: photo-to-text-converter
    env: python
    buildCommand: |
      mkdir -p tesseract
      cp -r tesseract/* tesseract/
      pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TESSDATA_PREFIX
        value: ./tesseract/tessdata
    packages:
      - tesseract-ocr
      - tesseract-ocr-eng 